# 참고
# GitHub: https://github.com/realm/SwiftLint
# Rules: https://realm.github.io/SwiftLint/rule-directory.html

# 규칙에서 제외
excluded:
    - Kindy/AppDelegate.swift
    - Kindy/SceneDelegate.swift

# 기본으로 켜져있던 설정 끔
disabled_rules:
    - multiple_closures_with_trailing_closure
    - opening_brace

# 기본으로 꺼져있던 설정 킴
opt_in_rules:
    - array_init
    - closure_end_indentation
    - closure_spacing
    - collection_alignment
    - comma_inheritance
    - convenience_type
    - discouraged_object_literal
    - empty_collection_literal
    - empty_count
    - empty_string
    - enum_case_associated_values_count
    - fallthrough
    - fatal_error_message
    - file_name_no_space
    - file_types_order
    - force_unwrapping
    - function_default_parameter_at_end
    - implicit_return
    - implicitly_unwrapped_optional
    - literal_expression_end_indentation
    - local_doc_comment
    - lower_acl_than_parent
    - missing_docs
    - modifier_order
    - multiline_arguments
    - multiline_arguments_brackets
    - multiline_function_chains
    - multiline_literal_brackets
    - multiline_parameters
    - multiline_parameters_brackets
    - no_extension_access_modifier
    - operator_usage_whitespace
    - optional_enum_case_matching
    - overridden_super_call
    - override_in_extension
    - pattern_matching_keywords
    - period_spacing
    - prefer_zero_over_explicit_init
    - prohibited_super_call
    - redundant_nil_coalescing
    - redundant_type_annotation
    - return_value_from_void_function
    - self_binding
    - shorthand_optional_binding
    - sorted_imports
    - static_operator
    - strict_fileprivate
    - toggle_bool
    - trailing_closure
    - unneeded_parentheses_in_closure_argument
    - unowned_variable_capture
    - untyped_error_in_catch
    - unused_capture_list
    - vertical_parameter_alignment_on_call
    - vertical_whitespace_closing_braces
    - vertical_whitespace_opening_braces
    - weak_delegate
    - yoda_condition

# 사용자 설정 규칙
line_length: 100
    
file_length:
    warning: 500
    
function_body_length:
    warning: 50

identifier_name:
  min_length:
    warning: 3
  excluded:
    - db
    - id
    - URL
    - url
